spring.application.name=ratelimiter

server.port = 8081
spring.data.redis.host=localhost
spring.data.redis.port=6379

rate.limit.maxRequests=5
rate.limit.windowSeconds=60

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always